// theme/stubs/vue/resources/js/Components/Theme/LinkButton.vue
<script setup>
import { Link } from '@inertiajs/inertia-vue3';
import { setButtonColor } from "@/Composables/setButtonColor.js";
const { buttonClasses } = setButtonColor();

const props = defineProps({
    href: {
        type: String,
        required: false,
        default() {
            return "#";
        },
    },
    outlined: {
        type: Boolean,
        required: false,
        default() {
            return false;
        },
    },
    rounded: {
        type: Boolean,
        required: false,
        default() {
            return false;
        },
    },
    elevate: {
        type: Boolean,
        required: false,
        default() {
            return false;
        },
    },
    small: {
        type: Boolean,
        required: false,
        default() {
            return false;
        },
    },
    color: {
        type: String,
        required: false,
        default() {
            return 'default';
        },
    },
});
</script>

<template>
    <Link :href="props.href" class="
      inline-flex
      items-center
      uppercase
      font-bold
      text-xs
      tracking-widest
      transition
      ease-in-out
      duration-150
    " :class="[
        props.rounded ? 'rounded-full' : 'rounded',
        props.elevate ? 'shadow-lg' : '',
        props.small ? 'px-2 py-1' : 'px-4 py-3',
        buttonClasses(outlined, color)
    ]">
    <slot />
    </Link>
</template>

// theme/stubs/react/resources/js/Components/Theme/LinkButton.jsx
import React from "react";
import { Link } from "@inertiajs/inertia-react";
import useButtonColor from "@/Hooks/useButtonColor";

export default function Button({
  className = "",
  processing,
  children,
  rounded,
  elevate,
  small,
  outlined,
  color,
  href
}) {
  const classFunction = () => {
    let classList =
      "inline-flex items-center uppercase font-bold text-xs tracking-widest transition ease-in-out duration-150";
    classList += rounded ? " rounded-full" : " rounded";
    classList += elevate ? " shadow-lg" : "";
    classList += small ? " px-2 py-1" : " px-4 py-3";
    classList += className !== "" ? " " + className : "";
    classList += " " + useButtonColor(outlined, color);
    return classList;
  };
  return (
    <Link
      href={href}
      type="button"
      className={classFunction()}
      disabled={processing}
    >
      {children}
    </Link>
  );
}
