// theme/stubs/vue/resources/js/Components/Theme/Mode.vue
<script setup>
import { ref, onUnmounted, watch } from 'vue';
import EasyButton from '@/Components/Button.vue';

const isDark = ref(false);

onUnmounted(() => {
    if (isDark.value) {
        document.body.classList.remove('dark')
    }
})

const toggleTheme = () => {
    isDark.value = !isDark.value
}

watch(() => isDark.value, () => {
    toggleClass()
})

const toggleClass = () => {
    console.log('hello');
    if (isDark.value) {
        document.body.classList.add('dark')
    } else {
        document.body.classList.remove('dark')
    }
}

</script>
<template>
    <easy-button @click="toggleTheme()" type="button">Mode Switcher</easy-button>
</template>

// theme/stubs/react/resources/js/Components/Theme/Mode.jsx
import React, { useState, useEffect } from "react";
import Button from "@/Components/Button";

const Mode = () => {
  const [isDark, setIsDark] = useState(false);
  const toggleTheme = () => {
    setIsDark(!isDark);
    console.log(isDark);
  }
  useEffect(() => {
    toggleClass();
  }, [isDark])
  
  const toggleClass = () => {
    if (isDark) {
        document.body.classList.add('dark')
    } else {
        document.body.classList.remove('dark')
    }
}
  return (
    <>
      <Button type="button">
       <span onClick={toggleTheme}>Mode Switcher</span>
      </Button>
    </>
  );
};

export default Mode;
