// theme/stubs/vue/resources/js/Components/Layout/Mode.vue
<script setup>
import { ref, onMounted, onUnmounted, watch } from 'vue';
import { usePage } from "@inertiajs/inertia-vue3";
import EasyButton from '@/Components/Theme/Button.vue';

const isDark = ref(false);

onMounted(() => {
    isDark.value = usePage().props.value.dark
})

onUnmounted(() => {
    if (isDark.value) {
        document.body.classList.remove('dark')
    }
})

const toggleTheme = () => {
    isDark.value = !isDark.value
}

watch(() => isDark.value, () => {
    toggleClass()
})

const toggleClass = () => {
    if (isDark.value) {
        document.body.classList.add('dark')
    } else {
        document.body.classList.remove('dark')
    }
}

</script>
<template>
    <EasyButton type="button" curve="full" :icon="(isDark) ? 'dark' : 'light'" @click="toggleTheme()" />
</template>

// theme/stubs/react/resources/js/Components/Theme/Mode.jsx
import React, { useState, useEffect } from "react";
import Button from "@/Components/Theme/Button";

const Mode = () => {
  const [isDark, setIsDark] = useState(false);
  const toggleTheme = () => {
    setIsDark(!isDark);
    console.log(isDark);
  }
  useEffect(() => {
    toggleClass();
  }, [isDark])
  
  const toggleClass = () => {
    if (isDark) {
        document.body.classList.add('dark')
    } else {
        document.body.classList.remove('dark')
    }
}
  return (
    <>
      <Button type="button" onClick={toggleTheme}>
       Mode Switcher
      </Button>
    </>
  );
};

export default Mode;
