// theme/stubs/react/resources/js/Components/Theme/Card.jsx
import React from 'react'

const Card = ({outlined,elevate,body,header,footer}) => {
    const classNameFunction = () => {
        let classNameList =
          "rounded-md bg-white dark:bg-gray-800";
        classNameList += outlined ? " border border-gray-200 dark:border-gray-900" : "";
        classNameList += elevate ? " shadow-md" : "";
        return classNameList;
      };
  return (
    <>
    <div className={classNameFunction()}>
        {header && (
            <div className="py-5 px-2 border-b border-gray-200 dark:border-gray-900">
            <span name="header">{header}</span>
        </div>
        )}
        {body && (
            <div className="py-5 px-2">
            <p>{body}</p>
        </div>
        )}
        {footer && (
            <div className="py-5 px-2 border-t border-gray-200 dark:border-gray-900">
            <span name="footer">{footer}</span>
        </div>
        )}
        
        
    </div>
    </>
  )
}

export default Card

// theme/stubs/vue/resources/js/Components/Theme/Card.vue
<script setup>
const props = defineProps({
    elevate: {
        type: Boolean,
        required: false,
        default() {
            return false
        }
    },
    outlined: {
        type: Boolean,
        required: false,
        default() {
            return false
        }
    },
    bgUrl: {
        type: String,
        required: false,
        default() {
            return ''
        }
    },
});
</script>

<template>
    <div class="rounded-md bg-white dark:bg-gray-800"
        :class="[(props.elevate) ? 'shadow-md' : '', (props.outlined) ? 'border border-gray-200 dark:border-gray-900' : '']">
        <div v-if="$slots.header" class="py-5 px-2 border-b border-gray-200 dark:border-gray-900">
            <slot name="header"></slot>
        </div>
        <div class="py-5 px-2">
            <slot></slot>
        </div>
        <div v-if="$slots.footer" class="py-5 px-2 border-t border-gray-200 dark:border-gray-900">
            <slot name="footer"></slot>
        </div>
    </div>
</template>
